In [147]:
class Trie:
    head = {}

    def add(self, word):
        cur = self.head
        for ch in word:
            if ch not in cur:
                cur[ch] = {}
            cur = cur[ch]
        cur['*'] = True

    def search(self, word):
        cur = self.head
        for ch in word:
            if ch not in cur:
                return False
            cur = cur[ch]
            
        if '*' in cur:
            return True
        else:
            return False
    def printf(self):
        print (self.head)

In [148]:
dictionary = Trie()
dictionary.add("hi")
dictionary.add("hello")
#dictionary.add("eye")
#dictionary.add("hey")


print(dictionary.search("hi"))
print(dictionary.search("hello"))
print(dictionary.search("hel"))
print(dictionary.search("he"))
dictionary.printf()

True
True
False
False
{'h': {'i': {'*': True}, 'e': {'l': {'l': {'o': {'*': True}}}}}}


In [4]:
new_text

"Game of Thrones is an American fantasy drama television series created by David Benioff and D B Weiss for HBO It is an adaptation of A Song of Ice and Fire George R R Martin's series of fantasy novels the first of which is A Game of Thrones The show was both produced and filmed in Belfast and elsewhere in the United Kingdom Filming locations also included Canada Croatia Iceland Malta Morocco and Spain The series premiered on HBO in the United States on April 17 2011 and concluded on May 19 2019 with 73 episodes broadcast over eight seasons"

In [45]:
Text = '''Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. The show was both produced and filmed in Belfast elsewhere in the United Kingdom.'''
import re
new_text = ''
punctuations = '''!.,'''
for character in Text:
    if character not in punctuations:
        new_text = new_text + character
from collections import Counter
split_text = Text.split(' ')
count = Counter(split_text)
most_freq_word_new = [key for key,valu in count.items() if valu == max(count.values())]

result =  {i: [] for i in most_freq_word_new}     #Create Dict with word as key and list as value
for index, word in enumerate(split_text):
    for i in most_freq_word_new:
        if word == i:
            #print (word)
            suffix_word =  split_text[index + 1]
            #print (suffix_word)
            prefix_word =  split_text[index - 1]
            #print (prefix_word)
            result[word].extend([suffix_word, prefix_word])  #Use list.extend to add to result.
            #print (result[word])
print(result)


{'and': ['D.', 'Benioff', 'filmed', 'produced'], 'in': ['Belfast', 'filmed', 'the', 'elsewhere']}


In [44]:
import re
from collections import Counter

Text = '''Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. The show was both produced and filmed in Belfast elsewhere in the United Kingdom.'''

split_text = Text.split(' ')
count = Counter(split_text)
most_freq_word_new = [key for key,valu in count.items() if valu == max(count.values())]

result =  {i: {"suffix_word": [], "prefix_word": []} for i in most_freq_word_new}     #Create Dict with word as key and list as value
for index, word in enumerate(split_text):
    for i in most_freq_word_new:
        if word == i:
            suffix_word =  split_text[index + 1]
            prefix_word =  split_text[index - 1]
            result[word]["suffix_word"].append(suffix_word)
            result[word]["prefix_word"].append(prefix_word)

print(result)

{'and': {'suffix_word': ['D.', 'filmed'], 'prefix_word': ['Benioff', 'produced']}, 'in': {'suffix_word': ['Belfast', 'the'], 'prefix_word': ['filmed', 'elsewhere']}}


In [42]:
import re
Text = '''Game of Thrones is an American fantasy drama television series created by David Benioff and D. B. Weiss for HBO. The show was both produced and filmed in Belfast elsewhere in the United Kingdom.'''
result = {
    'and' : {
    'suffix_word': [],
    'prefix_word': []
    },
    'in' : {
    'suffix_word': [],
    'prefix_word': []
    },

}
infindings=re.findall(r'([\w.]+) in ([\w.]+)',Text)
andfindings=re.findall(r'([\w.]+) and ([\w.]+)',Text)
for prefix,suffix in infindings:
    result['in']['prefix_word'] .append( prefix)
    result['in']['suffix_word'] .append( suffix)
for prefix,suffix in andfindings:
    result['and']['prefix_word'] .append( prefix)
    result['and']['suffix_word'] .append( suffix)
print(result)


{'and': {'suffix_word': ['D.', 'filmed'], 'prefix_word': ['Benioff', 'produced']}, 'in': {'suffix_word': ['Belfast', 'the'], 'prefix_word': ['filmed', 'elsewhere']}}


In [2]:
from datetime import datetime

In [7]:
log_file = r'C:\Users\makka\Desktop\example.log'

In [13]:
#Read log
def read_log(log_file):
    with open(log_file,'r') as f:
        print (f.read())

In [14]:
#open the file and write with date stamp
def write_log(log_file,name):
    log_time = str(datetime.now())
    with open(log_file,'a') as f:
        f.writelines("Entry logged as :{} by {}\n".format(log_time,name)) 

In [16]:
if __name__ == '__main__':
    name = input("what is youe name")
    print ("adding name to logfile")
    write_log(log_file,name)
    print ("")
    print ("log file contents are below")
    read_log(log_file)

what is youe namemanj
adding name to logfile

log file contents are below
Entry logged as :2019-06-18 15:11:34.611246 by mak
Entry logged as :2019-06-18 15:11:45.416673 by manj



In [ ]:
# Example Dictionary
author = {"name": "Hank", "color": "green", "shape": "circle"}

# A list of colors
colors = ["blue", "green", "red"]

# A list of dictionaries
favorite_colors = [
                      {
                          "student": "Mary",
                          "color": "red"
                      },
                      {
                          "student": "John",
                          "color": "blue"
                      }
                  ]

# Entry point for program
if __name__ == '__main__':
    print("The author's name is {}.".format(author["name"]))
    print("His favorite color is {}.".format(author["color"]))
    print("")

    print("The current colors are:")
    for color in colors:
        print(color)
    print("")

    # Ask user for favorite color and compare to author's color
    new_color = input("What is your favorite color? ")
    if new_color == author["color"]:
        print("You have the same favorite as {}.".format(author["name"]))
        print("")

    # See if this is a new color for the list
    #if new_color not in colors:
        print("That's a new color, adding it to the list!")
        colors.append(new_color)
        # Print update message about the new colors list
        message = ("There are now {} colors in the list. ".format(len(colors)))
        message += "The color you added was {}.".format(colors[3])
        print(message)
        print('new_co

In [31]:
# Example Dictionary
author = {"name": "Hank", "color": "green", "shape": "circle"}

# A list of colors
colors = ["blue", "green", "red"]

# A list of dictionaries
favorite_colors = [
                      {
                          "student": "Mary",
                          "color": "red"
                      },
                      {
                          "student": "John",
                          "color": "blue"
                      }
                  ]

# Entry point for program
if __name__ == '__main__':
    print("The author's name is {}.".format(author["name"]))
    print("His favorite color is {}.".format(author["color"]))
    print("")

    print("The current colors are:")
    for color in colors:
        print(color)
    print("")

    # Ask user for favorite color and compare to author's color
    new_color = input("What is your favorite color? ")
    if new_color == author["color"]:
        print("You have the same favorite as {}.".format(author["name"]))
        print("")

    # See if this is a new color for the list
    if new_color not in colors:
        print("That's a new color, adding it to the list!")
        colors.append(new_color)
        # Print update message about the new colors list
        message = ("There are now {} colors in the list. ".format(len(colors)))
        message += "The color you added was {}.".format(colors[3])
        print(message)
        print('new_color listr',colors)
    else: 
        pass

The author's name is Hank.
His favorite color is green.

The current colors are:
blue
green
red

What is your favorite color? mak
That's a new color, adding it to the list!
There are now 4 colors in the list. The color you added was mak.
new_color listr ['blue', 'green', 'red', 'mak']


In [103]:
ranklist = { 2000 : {1: ' Sara'  , 3 : 'Saj' , 2 : 'Pap' } , 
              2001 : {2: ' Sara'  , 1 : 'Saj' , 2 : 'Pap' } ,
              2002 : {3: ' Sara'  , 2 : 'Saj' , 1 : 'Pap' } ,
             }
    
    
a=[]
for year in ranklist:   
        for rank in ranklist[year] :
            if rank == 1:
                a.append(ranklist[year][rank])    


In [104]:
a

[' Sara', 'Saj', 'Pap']

In [3]:
lis=[
{"name": "Tom", "age": 10},
{"name": "Mark", "age": 5, "height":4},
{"name": "Pam", "age": 7, "weight":90}
]
test = []
for i in lis:
    print (i)
    for j in i:
        #print (j)
        test.append(j)
test
mylist = list(dict.fromkeys(test))
mylist

{'name': 'Tom', 'age': 10}
{'name': 'Mark', 'age': 5, 'height': 4}
{'name': 'Pam', 'age': 7, 'weight': 90}


['name', 'age', 'height', 'weight']

In [4]:
[x for x in (i.keys() for i in lis)]

[dict_keys(['name', 'age']),
 dict_keys(['name', 'age', 'height']),
 dict_keys(['name', 'age', 'weight'])]

In [130]:
# initialising dictionary 
ini_dict = {'a':1, 'b':2, 'c':3, 'd':2} 
  
# printing initial_dictionary 
print("initial_dictionary", str(ini_dict)) 
  
# finding duplicate values 
# from dictionary using flip 
flipped = {} 
  
for key, value in ini_dict.items(): 
    if value not in flipped: 
        flipped[value] = [key] 
    else: 
        flipped[value].append(key) 
  
# printing result 
print("final_dictionary", str(flipped))

initial_dictionary {'a': 1, 'b': 2, 'c': 3, 'd': 2}
final_dictionary {1: ['a'], 2: ['b', 'd'], 3: ['c']}


In [152]:
list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']
def four(list,n): 
    return [list[i::n] for i in range(n)] 
four(list, 3)

[['a', 'd', 'g', 'j', 'm'], ['b', 'e', 'h', 'k'], ['c', 'f', 'i', 'l']]

In [39]:
import re
line = " I am having a very nice day."
count = len(re.findall(r'\w+', line))
print (count)

7


In [1]:
import pandas as pd

In [43]:
df = pd.read_csv(r'C:\Users\makka\Desktop\m.txt', header=None)


In [44]:
df[df[0].str.contains("5.6")]

0
2      C   KB           1024               Mysql5.6
4      F   GB           1                  Mysql5.6

In [50]:
import re
infile = r'C:\Users\makka\Desktop\m.txt'
df_list = []
with open(infile) as f:
    for line in f:
        line = line.strip()
        columns = re.split('\s+', line, maxsplit=4)
        df_list.append(columns)

In [51]:
df = pd.DataFrame(df_list)
df[df[3].str.contains("5.6")]

0   1     2         3     4
2  C  KB  1024  Mysql5.6  None
4  F  GB     1  Mysql5.6  None

In [52]:
df_list

[['A', 'KB', '1024', 'MYsql', 'root'],
 ['B', 'GB', '1', 'ELK-6'],
 ['C', 'KB', '1024', 'Mysql5.6'],
 ['E', 'KB', '1024', 'ELK'],
 ['F', 'GB', '1', 'Mysql5.6']]

In [54]:
import shconfparser

INFO:root:Logging Time : 2019-09-17 11:41:55.133716


In [57]:
import inspect
src = inspect.getsource(shconfparser)
src

"import logging\nfrom datetime import datetime\n\nlogging.basicConfig(level=logging.DEBUG)\n# logging.basicConfig(filename='logs/shconfparser.log', level=logging.DEBUG)\nlogging.info('Logging Time : {}'.format(datetime.now()))\n"

In [21]:
from collections import Counter, OrderedDict
class OrderedCounter(Counter, OrderedDict):
    pass
d = OrderedCounter(input() for _ in range(int(input())))
print(len(d))
print(*d.values())

2
a b
c d
2
1 1


In [19]:
import numpy as np
N, M, _ = [int(x) for x in input().strip().split()]
a, b = map(lambda x: np.array([input().strip().split() for i in range(int(x))], int), [N, M])
print (np.concatenate((a, b), axis = 0))

2 2 2
1 2
3 4
5 6
7 8
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [11]:
n, m, p = map(int, input().split())
print(numpy.array([input().split() for _ in range(n+m)], int))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import numpy as np

n, m, p = map(int, input().split())    #assign n,m,p

source = " ".join(input() for _ in range(n))  #matrix1
matrix1 = np.array(source.split(), int)
matrix1.shape = (n, p)

source = " ".join(input() for _ in range(m)) #matrix2
matrix2 = np.array(source.split(), int)    
matrix2.shape = (m, p)

print(np.concatenate((matrix1, matrix2), axis=0)) #vertical axis=0

In [ ]:
import numpy as np
n,m,p=map(int,input().split())
lis=[]
for i in range(n+m):
    inp=input().split()
    lis.append(inp)
print(np.array(lis,int))

In [ ]:
k,l,z=input().split()
print(numpy.array([input().split() for _ in range(int(k)+int(l))] , int))

In [24]:
import numpy as np
n,m=map(int,input().split())
A = np.array([input().split() for i in range(n)], int)
B = np.array([input().split() for i in range(m)], int)
print(np.concatenate((A,B), axis=0))

1 2
2 3
4 5
6 7
[[2 3]
 [4 5]
 [6 7]]


In [ ]:
import numpy as np
N,M,P = map(int,input().split())
arr = []
for _ in range(N+M):
    row = np.array(list(map(int,input().split())))
    arr.append(row)
print(np.array(arr))