In [19]:
GoT = ['Tony', 'Rocket', 'Scott', 'Steve', 'Rocket', 'Natasha', 'Tony']
mylist = list(dict.fromkeys(GoT))
print(mylist)

['Tony', 'Rocket', 'Scott', 'Steve', 'Natasha']


In [24]:
di = {'elk': [{'url_1': 'http://localhost:8080/api/running',
                                 'url_2': 'http://localhost:8080/api/',
                                 'name': 'cat',
                                 'method': 'GET'}],
 'a': [{'url_1': 'http://localhost:8080/api/running',
                              'url_2': 'http://localhost:8080/api/',
                              'name': 'mouse',
                              'method': 'GET'}]}
 

for k,v in di.items():
    print (v[0]['name'])

cat
mouse


In [56]:
import re
m = re.search(r'.', d)

In [62]:
print (m.group(0))

b


In [1]:
s = ['language', 'Python', 'rocks']
some_text = "There is a %s called %s which %s."
x = some_text % tuple(s)
x = '{} {}'.format(*s)


In [2]:
x

'language Python'

In [4]:
s = {'first':['python','really'], 'second':'rocks'}
value=s['first'][1]
value

'really'

In [5]:
d = ['language', 'Python', 'rocks']
v = d

In [35]:
used = []
b = [3,4,5,5,6,6,7,7]
unique = [used.append(x) for x in b if x not in used]
used

[3, 4, 5, 6, 7]

In [64]:
a = [3,4,5,5,6,6,6,7,7]
c = set(a)
counts = {}
for i in a:
    if i in counts:
        counts[i] += 1
    else:
        counts[i] =1
counts

{3: 1, 4: 1, 5: 2, 6: 3, 7: 2}

In [65]:
t = [k*v for k,v in counts.items()]
t

[3, 4, 10, 18, 14]

In [66]:
max_index = t.index(max(t))
max_index

3

In [69]:
list(c)[max_index]

6

In [70]:
key, value = max(counts.items(), key=lambda x:x[1])
key, value

(6, 3)

In [57]:
from collections import Counter

a = [3,4,5,5,6,6,6,7,7]
e = Counter(a)

In [59]:
m = sorted(e.items(),key= lambda x: x[0]*x[1], reverse = True)
m

[(6, 3), (7, 2), (5, 2), (4, 1), (3, 1)]

In [63]:
m[0][0]

6

In [76]:
def reverse_string3(s):
    """Return a reversed copy of `s`"""
    chars = list(s)
    for i in range(len(s) // 2):
        tmp = chars[i]
        chars[i] = chars[len(s) - i - 1]
        chars[len(s) - i - 1] = tmp
    return ''.join(chars)

reverse_string3('TURBO')

'OBRUT'

In [85]:
def checkMagazine(magazine, note):
    
    if len(magazine) < len(note):
        return False
    magazine_counter = Counter(magazine)
    ransom_counter = Counter(note)
    for word, count in ransom_counter.items():
        if word not in magazine_counter or magazine_counter.get(word) < count:
            #return False
            return ('No')
    #return True
    return ('Yes')

In [86]:
checkMagazine('magazine', 'note')

'No'

In [1]:
from collections import Counter
# Complete the checkMagazine function below.
def checkMagazine(magazine, note):
    
    if len(magazine) < len(note):
        return False
    magazine_counter = Counter(magazine)
    ransom_counter = Counter(note)
    for word, count in ransom_counter.items():
        if word not in magazine_counter or magazine_counter.get(word) < count:
            #return False
            return ('No')
    #return True
    return ('Yes')


def checkMagazine(magazine, note):
    d = {}
    for word in magazine:
        d.setdefault(word, 0)
        d[word] += 1
    
    for word in note:
        if word in d:
            d[word] -= 1
        else:
            return False
    
    return all([x >= 0 for x in d.values()])

In [71]:
def checkMagazine(magazine, note):
    
        l1 = len(note)
        l2 = len(magazine)
        #magazine.sort()
        #note.sort()
        i = 0
        j = 0
        count = 0
        while i<l1 and j<l2:
                if note[i] == magazine[j]:
                        count += 1
                        i += 1
                j += 1
        if count == l1:
                print ('Yes')
        else:
                print('No')
checkMagazine('two times three is not four', 'two times two is four')

No


In [91]:
def aVeryBigSum(ar):
    res = 0
    for i in range(len(ar)):
        res += ar[i]
    return res 
aVeryBigSum([10,10,10])

30

In [95]:
def diagonalDifference(arr):
    # Write your code here
    l = len(arr[0])
    first_diagonal = sum([arr[i][i] for i in range(l)])
    second_diagonal = sum([arr[l-1-i][i] for i in range(l)])
    return (abs(first_diagonal - second_diagonal) )
###############
matrix_size = int(input())

current_x_one = 0
current_x_two = matrix_size - 1

sum_one = 0
sum_two = 0

for line in range(matrix_size):
    input_string = input().split(" ")
    sum_one = sum_one + int(input_string[current_x_one])
    sum_two = sum_two + int(input_string[current_x_two])

    current_x_one += 1
    current_x_two -= 1

print(abs(sum_one - sum_two))
###
n = int(input().strip())
dSumLeft = 0
dSumRight = 0
for i in range(n):
    matrixRow = input().split()
    dSumLeft += int(matrixRow[i])
    dSumRight += int(matrixRow[-(i + 1)])
##
n = int(input().strip())
dSumLeft  = 0
dSumRight  = 0
for i in range(n):
    matrixRow = list(map(int,input().strip().split(' ')))
    dSumLeft += int(matrixRow[i])
    dSumRight += int(matrixRow[n-i-1])
print(abs(dSumLeft - dSumRight))
#
print(abs(sum((lambda arr: int(arr[x]) - int(arr[len(arr) - x - 1]))(input().split()) for x in range(int(input())))))

30

In [10]:
import numpy as np


In [99]:

matrix = np.array(
         [[-2,  5,  3,  2],
          [ 9, -6,  5,  1],
          [ 3,  2,  7,  3],
          [-1,  8, -4,  8]])

diags = [matrix[::-1,:].diagonal(i) for i in range(-3,4)]
diags

[array([-2]),
 array([9, 5]),
 array([ 3, -6,  3]),
 array([-1,  2,  5,  2]),
 array([8, 7, 1]),
 array([-4,  3]),
 array([8])]

In [154]:
for j in range(-3,4):
    print (j)
    #print (matrix.diagonal(j))

-3
-2
-1
0
1
2
3


In [151]:
X = np.arange(100).reshape(10,10)
X2 = X[2:9,3:4]

In [152]:
X2

array([[23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83]])

In [155]:
mat = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
width, height = len(mat[0]), len(mat)

In [157]:
height

4

In [171]:
m = len(l)

l =[ -4, 3, -9, 0, 4, 1 ] 
def plusMinus(arr):
    po = 0
    ne = 0
    ze = 0
    for i in l:
        if i > 0:
            po += 1
        if i < 0:
            ne += 1
        if i == 0:
            ze += 1
    return (po/m, ne/m, ze/m)
plusMinus([ -4, 3, -9, 0, 4, 1 ])

(0.5, 0.3333333333333333, 0.16666666666666666)

In [174]:
n = float(input())
lst = [int(x) for x in input().split()]
print (format(len([x for x in lst if x > 0])/n, ".6f"))
print (format(len([x for x in lst if x < 0])/n, ".6f"))
print (format(len([x for x in lst if x == 0])/n, ".6f"))

5
123456
0.200000
0.000000
0.000000


In [175]:
a = [x for x in numbers if x >= 0: break]


SyntaxError: invalid syntax (<ipython-input-175-5f3ee95083c5>, line 1)

In [ ]:
def plusMinus():
    n = float(input())
    lst = [int(x) for x in input().split()]
    return (format(len([x for x in lst if x > 0])/n, ".6f")), (format(len([x for x in lst if x < 0])/n, ".6f")), (format(len([x for x in lst if x == 0])/n, ".6f"))

In [ ]:
plusMinus()

In [ ]:
n = float(input())
lst = [int(x) for x in input().split()]
def plusMinus(arr):

    return (format(len([x for x in lst if x > 0])/n, ".6f")), (format(len([x for x in lst if x < 0])/n, ".6f")), (format(len([x for x in lst if x == 0])/n, ".6f"))

In [ ]:
print ('hi')

In [5]:
def printMatrixDiagonal(mat, n): 
    # Initialize indexes of element to be printed next 
    i = 0
    j = 0
    k = 0
    # Direction is initially from down to up 
    isUp = True
  
     # Traverse the matrix till all elements get traversed 
    while k<n * n: 
         # If isUp = True then traverse from downward 
         # to upward 
        if isUp: 
            while i >= 0 and j<n : 
                print(str(mat[i][j]), end = " ") 
                k += 1
                j += 1
                i -= 1
  
              # Set i and j according to direction 
            if i < 0 and j <= n - 1: 
                i = 0
            if j == n: 
                i = i + 2
                j -= 1
  
         # If isUp = 0 then traverse up to down 
        else: 
            while j >= 0 and i<n : 
                print(mat[i][j], end = " ") 
                k += 1
                i += 1
                j -= 1
  
              # Set i and j according to direction 
            if j < 0 and i <= n - 1: 
                j = 0
            if i == n: 
                j = j + 2
                i -= 1
  
         # Revert the isUp to change the direction 
        isUp = not isUp 
  
# Driver program 
if __name__ == "__main__": 
    mat = [[1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9] ] 
  
n = 3
printMatrixDiagonal(mat, n) 

1 2 4 7 5 3 6 8 9 

In [31]:
mat = np.array([[1, 2, 3], 
        [4, 5, 6], 
        [7, 8, 9] ])
diags = [mat[::-1,:].diagonal(i) for i in range(-2,3)]
#diags.extend(mat.diagonal(i) for i in range(3,-4,-1))

for i in diags:
    print (i, end = '')

[1][4 2][7 5 3][8 6][9]

In [1]:
import sys

In [32]:
diags

[array([1]), array([4, 2]), array([7, 5, 3]), array([8, 6]), array([9])]

In [ ]:
Matrix = [[1, 2, 3, 4], 
          [5, 6, 7, 8], 
          [9, 10, 11, 12],
          [13, 14, 15, 16]]

def print_diags(Matrix):
    m, n = len(Matrix), len(Matrix[0])
    for offset in range(min(m,n)):
        diag_upper = [row[i + offset]
                      for i, row in enumerate(Matrix)
                      if 0 <= i + offset < n]
        if offset != 0:
            diag_lower = [row[i - offset]
                      for i, row in enumerate(Matrix)
                      if 0 <= i - offset < m]
            print(diag_upper, diag_lower)
        else:
            print(diag_upper)
print_diags(Matrix)

In [ ]:
np_m = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])

diags = [np_m[::-1,:].diagonal(i) for i in range(-np_m.shape[0]+1,np_m.shape[1])]
for i in diags:
    print (i, end = '')

In [ ]:
str = 'Makbul is 30 and Saw is 29 and Man is 30'
digit = [int(s) for s in str.split() if s.isdigit()]
string = [(s) for s in str.split() if s.isalpha()]
names = string[0::3]
dict(zip(names,digit))
#import re
#names1 = re.findall(r'(\w+(?=\s*is[^/]))', str)
#names1
#igit1 = re.findall(r'(\d+)', str)
#igit1

In [3]:
test = {'avglen': 4.419354838709677, 'count:': 93, 'mosts:': 'your', 'longs:': ['stretched'], 'shorts:': ['i', 'a'],}
print("{" + "\n".join("{}: {}".format(k, v) for k, v in test.items()) + "}")


{avglen: 4.419354838709677
count:: 93
mosts:: your
longs:: ['stretched']
shorts:: ['i', 'a']}


In [4]:
dictionary1 = {'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}
dictionary2 = {'value1': 'AAA', 'value3': 'CCC'}
for k, v in dictionary1.items():
    print (dictionary2.get(v, v))

AAA
value2
CCC


In [136]:
d1 = {'db1': [{'url': 'http://localhost:8080/api', 'cmd': 'test\\nshow databases ', 'request': 'POST'}], 'db2': [{'url': 'http://localhost:8080/api', 'cmd': 'test\\nshow databases ', 'request': 'POST'}]}

In [137]:
d2 = {'cmd': 'test'}

In [138]:
#{k: d2.get(k, v) for k, v in d1.items()}

In [139]:
{k1:{**v1[0], **d2} for k1,v1 in d1.items()}


{'db1': {'url': 'http://localhost:8080/api', 'cmd': 'test', 'request': 'POST'},
 'db2': {'url': 'http://localhost:8080/api', 'cmd': 'test', 'request': 'POST'}}

In [133]:
d3

{None}

In [159]:
dictionary2  = {'device_running_config_cmd': 'makku'}
#result = {k1:{**v1[0], **dictionary2} for k1,v1 in dictionary1.items()}
for k1,v1 in test.items():
    result = ({k1:{**v1[0], **dictionary2}})
    #print (result)

In [2]:

def maxSubArraySum(a,size): 
      
    max_so_far =a[0] 
    curr_max = a[0] 
      
    for i in range(1,size): 
        curr_max = max(a[i], curr_max + a[i]) 
        max_so_far = max(max_so_far,curr_max) 
          
    return max_so_far 
  
# Driver function to check the above function  
a = [-2, -3, 4, -1, -2, 1, 5, -3] 
print("Maximum contiguous sum is" , maxSubArraySum(a,len(a)) )

Maximum contiguous sum is 7


In [9]:
from sys import maxsize 
def maxSubArraySum(a,size): 
  
    max_so_far = -maxsize - 1
    max_ending_here = 0
    start = 0
    end = 0
    s = 0
  
    for i in range(0,size): 
  
        max_ending_here += a[i] 
  
        if max_so_far < max_ending_here: 
            max_so_far = max_ending_here 
            start = s 
            end = i 
  
        if max_ending_here < 0: 
            max_ending_here = 0
            s = i+1
  
    print ("Maximum contiguous sum is %d"%(max_so_far)) 
    print ("Starting Index %d"%(start)) 
    print ("Ending Index %d"%(end)) 
a = [-2, -3, 4, -1, -2, 1, 5, -3] 
maxSubArraySum(a,len(a)) 

Maximum contiguous sum is 7
Starting Index 2
Ending Index 6


In [11]:
import re
multiline_text=\
"""

1 00:00:00,130 --> 00:00:01,640

where you there when it happened?

Who else saw you?

2 00:00:01,640 --> 00:00:03,414

This might be your last chance to

come clean. Take it or leave it.
"""

lines = multiline_text.split('\n')
#print (lines)
dict = {}
current_key = None;

for line in lines:
    #print (line)
    is_key_match_obj = re.search('([\d\:\,]{12})(\s-->\s)([\d\:\,]{12})', line)
    if is_key_match_obj:
        current_key = is_key_match_obj.group()
        print (current_key)
    


00:00:00,130 --> 00:00:01,640
00:00:01,640 --> 00:00:03,414


In [ ]:
filims={'rak':[20,2],'val':[15,5],'prak':[20,8]}
while True:
    choice=input('Which filim would like to watch: ').strip().lower()
    if choice in filims:
        age=int(input('What is your age: ').strip())
        if age >= filims[choice][0]:
            num_seats=filims[choice][1]
            if num_seats>0:
                print("Enjoy! the filim")
                num_seats=filims[choice][1]-1
            else:
                print("Sorry sold out")
        else:
            print('Sorry we dont have that filim')

Which filim would like to watch: rak
What is your age: 21
Enjoy! the filim
Which filim would like to watch: rak
What is your age: 9
Sorry we dont have that filim


In [ ]:
import pdb
names=['musthu','mahir','khader']
while True:
    #pdb.set_trace()
    print('Hellow my name is abu')
    a=input('name').strip().lower()
    if a in names:
        print('Hi {} welcome to python world'.format(a))
        z=input('y/n').strip().lower()
        if z== 'y':
            names.remove(a)
            print('Here the new list: ')
            print(names)


Hellow my name is abu
namemusthu
Hi musthu welcome to python world
y/ny
Here the new list: 
['mahir', 'khader']
Hellow my name is abu


In [5]:
result = {
  'a': lambda x: x * 5,
  'b': lambda x: x + 7,
  'c': lambda x: x - 2
}[value](x)

NameError: name 'value' is not defined

In [6]:
dictio =[{'key1':'value1'}, {'key1':'value2'}]
{'key1': ['value1', 'value2']}
input > {'A':[1,2,3,4], 'B':[5,6], 'C':[7,8,9], 'D':[10]}
Output >> {'A': [1, 2], 'B': [5, 6], 'C': [7, 8], 'D': [10]}
input >> 10 20 20 10 10 30 50 10 20
out put-2 '1,2,3 4 5 6 7 8 9 10'
dict = {"a" : [1,2,3,4] ,"b":[34,45,4567],"c":[34]}

newDict = {}
for key,value in dict.items():
    newDict[key]= value[0:2]


print (newDict)


out put- {'a': [1, 2], 'b': [34, 45], 'c': [34]}




dict = {"a" : [1,2,3,4] ,"b":[34,45,4567],"c":[34]}

newDict = {}
for key,value in dict.items():
    newDict[key]= value[0:2]


print (newDict)


out put- {'a': [1, 2], 'b': [34, 45], 'c': [34]}



2-dict = {"a" : [1,2,3,4] ,"b":[34,45,4567],"c":[34]}

newDict = {}
for key,value in dict.items():
    newDict[key]= value[0:2]


print (newDict)


out put- {'a': [1, 2], 'b': [34, 45], 'c': [34]}


dict = {"key1":"value1","key2":"value2"}
newDict= {}
newDict["key1"]=list(dict.values())
print (newDict)





{'key1': ['value1', 'value2']}



SyntaxError: invalid syntax (<ipython-input-6-746217ecc42e>, line 5)

In [12]:
dictio =[{'A':[1,2,3,4], 'B':[5,6,77,92], 'C':[7,8,9], 'D':[10]}]
newDict = {}
for d in dictio:
    for key,value in d.items():
        newDict[key]= value[0:2]
print (newDict)


{'A': [1, 2], 'B': [5, 6], 'C': [7, 8], 'D': [10]}


In [8]:
dic = {'key1': ["value1", "value2"],'key2': ["value77", "something"] }
keys = list(dic.values())
flaten_list = []
for key in keys:
    if isinstance(key, list):
        flaten_list.extend(key)
    else:
        flaten_list.append(key)

'value77' in flaten_list

True

In [9]:
flaten_list

['value1', 'value2', 'value77', 'something']

In [12]:
out =    {'10.30.24.3': {'DELETE': 1,
                'GET': 5,
                'POST': 1,
                'PUT': 3},
 '192.168.10.20': {'DELETE': 1,
                   'GET': 6,
                   'POST': 3,
                   'PUT': 3},
 '98.5.45.3': {'DELETE': 2,
               'GET': 6,
               'POST': 2,
               'PUT': 2}}
import pandas as pd
df = pd.DataFrame([out])
df.head()


cols = ['IP', 'DELETE', 'POST', 'PUT','GET']
pd.DataFrame(out).T.reset_index().rename(columns={'index':'IP'})[cols]

IP  DELETE  POST  PUT  GET
0     10.30.24.3       1     1    3    5
1  192.168.10.20       1     3    3    6
2      98.5.45.3       2     2    2    6